pipeline:
  name: Ci-build-pod
  identifier: Cibuildpod
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.AbhinandanGit
        repoName: charts
        build: <+input>
  stages:
    - stage:
        name: build-pod
        identifier: buildpod
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    connectorRef: account.harnessImage
                    image: docker
                    shell: Sh
                    command: echo <+codebase.commitSha>
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.kube
              namespace: abhinandan
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
    - stage:
        name: rest
        identifier: rest
        template:
          templateRef: account.newtest2
          versionLabel: "1"
          templateInputs:
            type: Deployment
            spec:
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
