pipeline:
  name: Git
  identifier: Git
  projectIdentifier: Git_Exp
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: shell lijo
        identifier: shell
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: shell
                  identifier: shell
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "Lord Lijo"
                          Lijo
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
        variables:
          - name: test
            type: String
            description: ""
            value: <+input>
    - stage:
        name: shelltemp
        identifier: shelltemp
        template:
          templateRef: stagetemp2
          versionLabel: "2.0"
    - stage:
        name: sample
        identifier: sample
        template:
          templateRef: stagetemp
          versionLabel: "1.0"
